### ISSUE TITLE
switch classList polyfill

### ISSUE THREAD

**Issue by kmathmann** [TobitSoftware/chayns-js#1]
The current classList polyfill doesn't allow to use `add` with multiple classes in IE 10/11.

The current polyfill based on [classList.js](https://github.com/eligrey/classList.js). But he is behind the original one.

 So we should switch to the original [classList.js npm package](https://www.npmjs.com/package/classlist.js) where the IE 10/11 issue is already fixed.

**Comment by kmathmann** [comment]
The `classlist-polyfill` is listed under devDependencies and under dependencies. The devDependency should be removed.

**Comment by SteffenHo** [comment]
Hello,
Thank you for your issue.
We updated the polyfill to version 1.2.0 and now you can add multiple classes in IE 10/11.
