### ISSUE TITLE
bug in posting editor

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#12]
hi guys,

I needed to edit a facebook posting within "Aktuell" tapp. I was inside Android App and switched to manager mode. Appending the new text was hard because the cursor jumped to first place randomly and mulitple times. This happended in both input fields.

afterwards I saw a second little bug. I used to type an arrow made of minus and a greater-than sign. On the articles detail page it is okay, but on the "Aktuelles" stream it is shown as `-&gt;`

**Comment by SteffenHo** [comment]
Hello, 

This is a problem of the "Aktuell"-Tapp and we cannot fix it in chayns-js. I have passed it to the appropriate places. 
You can see the ReleaseNotes of this Tapp in your chaynsAdministration chayns->support->ReleaseNotes on your ChaynsSite.
