### ISSUE TITLE
chayns.updateNavigation()

### ISSUE THREAD

**Issue by niklasschemmer** [TobitSoftware/chayns-js#13]
In my tests the updateNavigation method does not switch to the given tappId after updating the Navigation. And the tappId is not optional.

**Comment by SteffenHo** [comment]
Hello @niklasschemmer ,
Can you pleace send me the code you had used to test it?
That would help me to figure out what happend.

**Comment by niklasschemmer** [comment]
I think I used the exact example from the doku : chayns.updateNavigation(tappId, {
  'stateOnly': false, 
  'updateTapp': true 
});
And I tried chayns.updateNavigation(tappId);
In my case it does not switched the Tapp.
I used selectTapp() Tapp method, to fix it.

**Comment by SteffenHo** [comment]
Hello, 

We cannot comprehend you Problem. When you use:
```js
 chayns.updateNavigation(71519); 
```
 The site will switch to the Tapp and update the navigation.
