### ISSUE TITLE
confirm dialog cannot show content

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#14]
The dialogs height need to be limited to a max value.

When content is long, the dialog is larger than the screen and the buttons get unreachable.

Wrapping the content to a div with `max-height` and` overflow:auto` helps only on desktop/website but within the app (android tested) scrolling does not work - also the max-height is not working here. Content is hidden behind the buttons...

tip: limit to a max-height so every content is seen also on mobile app
tip 2: bound the escape key on desktop to the navigateBack() to cancel the dialog as on mobile

thank you

**Comment by SteffenHo** [comment]
Hello, 

The Chayns-js serves as a communication system between our ChaynsTapps and the ChaynsWeb/App. We send information like text or  buttons from the Tapp to ChaynsWeb. 

The Chayns-js cannot set the heigh of the dialog, that isnt paart of the general Api. 
You can create a fork of this projekt and customise it in the way you need it.
