### ISSUE TITLE
Fatal error on first tapp

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#15]
The first tapp in the tapp list must be called on start. Since a couple of days the first tapp is NOT called first anymore if it is not shown in the navigation (checkbox option).
Please repair this. First tapp is first, no matter if it is shown in the nav or not - as it was correct before... Thank you guys

**Comment by pjanning** [comment]
This bug has nothing to do with the API. Please place it correct in the future.

**Comment by meldau** [comment]
So please offer a correct target for platform bug^^ Intercom support team is not, developers should be... So maybe you should create a platform repository
