### ISSUE TITLE
no chayns environment found

### ISSUE THREAD

**Issue by ratneshlambhate** [TobitSoftware/chayns-js#16]
After setup node server and clone the git repository.

run the command npm run start

the index.html i tried

<html>
<body>
<script src="chayns.js"></script>

<script>
console.log(chayns.env);
 chayns.ready
  .then(function resolved(){
   console.log("chayns is ready, environment is loaded", chayns.env);
  })
  .catch(function rejected(){
   console.log("no chayns environment found");
  })
  .then(function always(){
   console.log("Will always be executed");
  });
</script>

</body>
</html>

in console it showing "no chayns environment found".

I tried <script src="https://chayns-res.tobit.com/API/V3.1/js/chayns.min.js"></script> but same issue.

Please assist me .

**Comment by pjanning** [comment]
Did you run the code in a valid chayns environment such as chayns-web, chayns-web-light or in a chayns app? Otherwise the chayns.ready-promise will always be rejected.

**Comment by ratneshlambhate** [comment]
I am using chayns-js environment

**Comment by pjanning** [comment]
Chayns-js is no chayns-environment. Chayns-js is an api to control an chayns-environment.

Have a look at our getting started: https://github.com/TobitSoftware/chayns-js/wiki/Getting-Started#step-3---add-the-tapp
