### ISSUE TITLE
Tooltip truncated in Intercom Plugin

### ISSUE THREAD

**Issue by uvalmsick** [TobitSoftware/chayns-js#18]
![image](https://user-images.githubusercontent.com/12053271/28780574-80ff9eb6-7607-11e7-830f-2a16bf8fbd3e.png)
The Tooltip ist not full visible in an Intercom Plugin

**Comment by SteffenHo** [comment]
Hello uvalmsick,
Can you please send me a Intercom message like these, so that I can reproduce this problem?

**Comment by uvalmsick** [comment]
ok, message is send
