### ISSUE TITLE
Nessecary Polyfills for IE

### ISSUE THREAD

**Issue by niklasschemmer** [TobitSoftware/chayns-js#19]
Hi, there some functions in IE, that need a polyfill like findIndex() and includes().
Otherwise it will throw an error.
Here are my suggestions:

String.prototype.includes = function(){               
        return String.prototype.indexOf.apply(this,  arguments) !== -1;            
};

Array.prototype.findIndex = function(callback){
   for(var  i=0;i<this.length;i++){
        var found =  callback(this[i]); 
                 if(found ==  true){ 
                       return i;
                 }
           } 
     return -1;
 };

**Comment by SteffenHo** [comment]
Hello niklasschemmer, 

ChaynsJS supports polyfills which the project need. If your tapp need this polyfills you have to include it by yourself.
