### ISSUE TITLE
chayns.showTitleImage();

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#27]
Please, could you extend chayns.showTitleImage(); with a new image parameter to set header-image dymanically. Or create something like chayns.setTitleImage({url});

That would be helpful. Thanks

**Comment by SteffenHo** [comment]
Hello @meldau 

Thank you for your suggestion. We checked your suggesstion and we added it to  our tasks. Before I can add it to chayns-js our Web and App DevelopTeam must implement this function . 

We will inform you when the ChaynsCall is available in ``chayns-js``.

**Comment by meldau** [comment]
Any news since november, @SteffenHo ?

**Comment by SteffenHo** [comment]
Hello @meldau,

Sorry that it takes such a long time, we added a call which you can use to set the title image.  chayns.setTemporaryDesignSettings( component, param)

You can use the call like this:

1.  ```chayns.setTemporaryDesignSettings('titleImageVisability', false)``` 
The Call will show or hide the title image

2. ```chayns.setTemporaryDesignSettings('titleImageUrl', '//images.tobit.com/locations/153008/38dd6dc9-b6b3-4d96-baaf-0bd66a96cc46.png')```
The call will change the title image of your website.

3. ```chayns.setTemporaryDesignSettings('locationIcon', 'https://chayns.tobit.com/storage/60038-22141/Images/icon-72.png')```
This call will change the icon of your site.

4. ```chayns.setTemporaryDesignSettings('imageOverlay', 'https://images.tobit.com/locations/1/Tapps/247353_Parallax.png?_=1527161393')```
This call will add a secound layer to your title image.

5. ```chayns.setTemporaryDesignSettings('backgroundColor', '#ff0000')```
This call will change the background color.

You can use this call in chayns®Web, there are still some problems in chayns®Web mobile, when you want to change the title image, we will fix it as soon as possible. You cannot use this call in our chayns®Apps but our AppDevelopment will implement it soon.
