### ISSUE TITLE
chayns.dialog.select  listitem with a NULL value

### ISSUE THREAD

**Issue by uvalmsick** [TobitSoftware/chayns-js#3]
![screenshot](https://cloud.githubusercontent.com/assets/12053271/24802378/16e8901e-1ba8-11e7-9f5e-02b1fd8c25e9.jpg)

chayns.dialog.select:

when you Add a listitem with a Value of NULL as Name, the dialog crached with die Message above

**Comment by kmathmann** [comment]
This was a problem of the website. 
I fixed this, now the select dialog at the website no longer requires a name if an image and a value are given, else it ignores the item.
