### ISSUE TITLE
isPWA

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#30]
Hi, is there a chance to get an `isPWA` falg next to `isApp` or `isDesktop` in environment object so I know if a call is made on mobile browser window or was started as a web app?

**Comment by SteffenHo** [comment]
You can use  ``` window.matchMedia('(display-mode:  standalone)').matches```  to find out if you are in a PWA. At the moment we won't add this  flag because mobileWebsite and PWA should have the same feeling and work  the same way.
