### ISSUE TITLE
Adminstatus

### ISSUE THREAD

**Issue by uvalmsick** [TobitSoftware/chayns-js#31]
can we get the AdminMode in the chayns.env.user variables?

Currently we  must use Apdata:

chayns.ready.then(data => console.debug(data.AppUser.AdminMode));

**Comment by SteffenHo** [comment]
Hello @uvalmsick 

You can find the admin mode in ```chayns.env.user.adminMode```. When you use ```chayns.setAdminSwitchCallback()```, the flag will be automatically set correct and the tapp will not longer be reloaded.

Best regards
Steffen
