### ISSUE TITLE
HTML inkonsitent

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#32]
When using chayns.dialog.select() list items texts (value) can include HTML-Tags in browser. But calling the same in app / on smartphone only the source code is displayed to the user. Please parse valid HTML everywhere.
 Thx

`chayns.dialog.select({..., list: [{"name":"<b>HTML</b> tag included","value":0}], ... })...`

**Comment by JonasGossens** [comment]
I fixed this problem. It's now possible to use html content in select dialog items.
