### ISSUE TITLE
broken navigation

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#34]
when switching off header image by javascript call `chayns.hideTitleImage()` on an tapp the users login name (next to users circled picture) overlapses the burger menu button on right top corner of the screen (on android app, others not testet) - so **you cannot click to the main menu ever again**. please repair so people can navigate further on. thx.

btw: the profile pic is cut in half, too. Top half is not seen on screen when cover is switched off

**Comment by SteffenHo** [comment]
Hello, 
This problem is fixed in android app version 5.660.
