### ISSUE TITLE
custom modal window

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#35]
Could you extend chayns.dialog by a customizable iframe content, please.

for example `chayns.dialog.custom(url);`

The dialog is the only function to create a modal container that is flying over whole page. That's helpful espeacially in small tapps or even widgets. Opening a modal window and fill it by myself including return values and buttons would be the only way to offer a good user experiene where is less space. The chayns environment should replace siteid placeholder within the given url for security reasons...
Thank a lot!

**Comment by JonasGossens** [comment]
Hi Marcus,
for a custom modal window, you can use the iFrame-dialog. It allows you to show an iFrame in a dialog and communicate with the tapp using a message-based communication system. 
It's documented in the wiki: https://github.com/TobitSoftware/chayns-js/wiki/Dialogs#iframe-dialog
