### ISSUE TITLE
set button color in confirm dialogs

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#36]
hi guys,

sometimes it is helpful for the users to set different colors to each button in a confirm dialog, e.g. to priorize a choice or to warn also visually.

please add background and font color settings next to `name` and `buttonType` into object "buttons" for `chayns.dialog.confirm(title, message, buttons)`

thanks a lot

**Comment by SteffenHo** [comment]
Hello @meldau, 
You can set the button color when you set the text color and the background  color in the button object like this example:  
```javascript
 chayns.dialog.confirm('Title', 'message', [{   
     'text': chayns.dialog.buttonText.YES,
     'buttonType': chayns.dialog.buttonType.POSITIVE,
     'textColor': "#000000", 
     'backgroundColor': "#0b7529",
       
 }, {   
     'text': chayns.dialog.buttonText.NO,
     'buttonType': chayns.dialog.buttonType.NEGATIVE  
 }]).then(console.log)
```

This Feature is supported in iOS and in Android. The text color in Android is  supported from version 5.713. chayns®Web does not support textColor and  backgroundColor, but they will implement it.

Best regards
Steffen

**Comment by meldau** [comment]
thanks a lot!

**Comment by SteffenHo** [comment]
Hello @meldau ,
You can use it now in chayns®Web, too.
