### ISSUE TITLE
Environmental Variables in Widgets/iframes

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#37]
Hi guys,

within widgets I get information about if the call **_is_** a widget (isWidget=true) but there is no identifier yet to
a) decide if call is within iframe 1, iframe 2 or iframe 3 on same page/tapp
b) decide if call is the same iframe on the same page/tapp but in another session (eg a day later)

So, we need an identifier, an unique id for each widget, that is set on creation and does not change during lifetime. It's urgent, please.

thx a lot
Marcus

**Comment by SteffenHo** [comment]
Hello @meldau ,

You can use ```window.name + chayns.env.site.tapp.parent.id``` in Iframes to get a  unique Id. The parentTappId is set from the Pagemaker™

Best wishes,
Steffen

**Comment by meldau** [comment]
Hello @SteffenHo ,
the window.name helps on different situations, thanks. But it is not unique (if you delete the last one and create a new it get's the same name because it is based on counting the iframes) and should change when url changes. So a unique id or hash would be extremly helpful. Thx for rethinking about closing this issue.

greetings to Ahaus
Marcus

**Comment by meldau** [comment]
Hi @SteffenHo,

anything new on identifying diefferent widget frames on one page? I need this identifier **urgently**, most likely direct via GET-parameter on first call. Thanks

**Comment by JonasGossens** [comment]
Hi @meldau,

do you need
- a sessionId, which you can use in combination with window.name and chayns.env.site.tapp.parent.id to get an unique Id for each frame, that will be gone after closing the browser?
or
- an unique widgetId, that is independent from the session and will be the same at every client?

greetings,
Jonas

**Comment by meldau** [comment]
Hi Jonas,
most important ist a unique widget identifier that can be a simple number counting on on each tapp. So I can use in combination with TappID. But it should count up on every creation (not reused when last widget is deleted before a new creation: create 1, create 2, delete 2 => next create may not recreate 2 but 3) and should be used as GET parameter.
( When we also could get a users session identifier - even as GET - would be extremly helpful. Not even in widgets but allover the project. )

Thx Jonas!

geetings 
Marcus

**Comment by JonasGossens** [comment]
Hi Marcus,
we've changed the name of new widget iframes in the beta version of the new pagemaker. You will get a GUID as identifier. 
To create your own session identifier, you have to generate an id and store it in the browser's session storage.

greetings,
Jonas
