### ISSUE TITLE
chayns.setSubTapp()

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#38]
Hi,

when creating a subTapp() /w `exclusiveMode:true` from a non-exclusiveMode tapp the navigation block will slide out correctly, but content box still keeps its width.

The content box should get wider when opening exclusive mode - or narrower vice versa - no matter which mode was active within the calling tapp.

thx
Marcus

**Comment by SteffenHo** [comment]
Hello @meldau 

Our ChaynsWeb-Team has fixed that issue this morning. 
I tested it with this call:
```js 
chayns.setSubTapp({
 'tappID': 999999999,
 'url': 'https://mashup.tobit.com/tapps/eventsV3/index.html?TappID=71519&OS=webshadow&color=37913C&font=1&colormode=1&lang=de&AppVersion=1.390&_=1535449298576&translang=de',
 'name': 'Event-Subtapp',
 'color': '#ffff00',
 'sortID': 8989,
 'icon': 'fa-plus',
 'buttonName': 'Button',
 'replaceParent': false,
isExclusiveView: true
}); 
```

Best wishes
Steffen

**Comment by meldau** [comment]
Yes, thanks @SteffenHo . I have not tested again, but my usecase "calling with exclusiveMode=true from non-exclusiveMode" is running correctly in brwoser now. 

That was quick! Thanks
