### ISSUE TITLE
Chayns-js start package update?

### ISSUE THREAD

**Issue by Toastbrotbaby** [TobitSoftware/chayns-js#39]
Can you update the chayns-js project with correct dependencies? some packages are deprecated and there are some compatibility issues.
It would be much easier for new members if they could download a error free project. ;-)
thx

**Comment by KaiSchniggendiller** [comment]
Hey @Toastbrotbaby,  pls specify ur problems, u can easily build this project. It's true that some depencencies are out of date and we will update them 👍

**Comment by KaiSchniggendiller** [comment]
We updated the packages and webpack configs.
