### ISSUE TITLE
delegate-function support for more browser

### ISSUE THREAD

**Issue by michael-braun** [TobitSoftware/chayns-js#4]
The delegate function in src/utils/delegate.js could support more (older) browser when you add a polyfill for Element.matches or directly use the prefixed versions from the other major browsers (e.g. mozMatchesSelector) on line 13.
It is only necessary if you want to support older browsers without errors too.

See: [https://developer.mozilla.org/de/docs/Web/API/Element/matches](https://developer.mozilla.org/de/docs/Web/API/Element/matches#Polyfill) (polyfill-section)

**Comment by SteffenHo** [comment]
Hello, 
Thank you for your issue.
The delegate function will now be supported in older browsers like the FireFox 21.0.0
