### ISSUE TITLE
zIndex-Bug

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#40]
hello,
elements created by chayns.showOverlay() and chayns.showWaitCursor() are lying behind the elements that are shown by the iframe page. please repair, thx

**Comment by sebkortenbrede** [comment]
Hello @meldau
We have lowered the z-index of the overlay so the waitcursor is correctly displayed on top of it.

**Comment by meldau** [comment]
Hallo @sebkortenbrede 

you repaired half of the bug. I can see it within an API-Tapp with a form.
The spinner is on top now, but the overlay is still lying behind content elements like input fileds. An overlay should cover _all_ elements.

thx Marcus
