### ISSUE TITLE
button click missing

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#41]
Hi,

till yesterday dialogs with things to choose (chayns.dialog.select(config)) fired buttonType=1 "okay", when the user has clicked on one item. That was good usability, because one single click did the job!

Now you switched to another styling (option bubbles with checkmarks left to each entry) and choosing one item doesn't fire the event anymore. Because a single click was good usability none of my select dialogs has an additional okay button - because it was not needed. So no user can take a choice anymore! Please return to _**a single click means "I choose this"**_ - or better give us the option for both. But you cannot change the known default behavior. All pages select dialogs are broken now!

thanks for rushin 
Marcus

**Comment by meldau** [comment]
This bug also causes errors in your own environment: due to not switching to correct API choice on the choosebutton I cannot create a new DeveloperTapps on tspn site. Please check, @pjanning. Thx

**Comment by JonasGossens** [comment]
We already fixed this problem. A single click on an item fires buttonType=1 if mutltiselect is not active.
