### ISSUE TITLE
Store custom data for tapp

### ISSUE THREAD

**Issue by manuelbostanci** [TobitSoftware/chayns-js#42]
Hi guys,
is there any possibility to store configuration data for e.g. a custom tapp? 
Years ago, when I created a custom tapp, one could pass custom parameters with the tapp url.
What is your approach now for this? 

Thanks!

**Comment by ledicana** [comment]
Hi Manuel,

you can still add parameters to the tapp URL, when you create a custom tapp. You can then access these parameters in your tapp through chayns.env.parameters. 

Was that the solution you were looking for?

**Comment by manuelbostanci** [comment]
Partly! ;)
I didn't know, that I can access the params via chayns.env.parameters. 

My tapp contains a code snipped to display a liveticker. For each game, the ticker id must be configured.
I would like to have a more ux-friendly way to manage the tapp data. Do you have any idea how to do that?
Thanks!

**Comment by sebkortenbrede** [comment]
Hi Manuel,

you can store key-value pairs for your Tapp with `chayns.storage.set('foo', 'bar')` and access them with `chayns.storage.get('foo')`. Both methods return a promise. Storing objects or other data types is possible too.
