### ISSUE TITLE
JS Intercom send failed

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#45]
Hi guys,

sending messages to page don't work anymore as described in https://github.com/TobitSoftware/chayns-js/wiki/Basic-Functions#chaynsintercomsendmessagetopageconfig---snippet

Response { type: "cors", url: "https://sub54.tobit.com/rest/api/user/6***6/message", redirected: false, status: 401, ok: false, statusText: "Unauthorized", headers: Headers, body: ReadableStream, bodyUsed: false }

Yes, I'm logged in. And I can reproduce in differnt browsers and with different logins.

**Comment by JonasGossens** [comment]
Hi Marcus,

unfortunately, we couldn't reproduce this problem. But we investigated that you sent requests without an access token to the endpoint. 
Can you give us more informations about the problem or send us the url to your tapp?

Jonas

**Comment by meldau** [comment]
Hi Jonas, no I don't send without token. Everything is running unchanged since months.

I check chayns.env.user.isAuthenticated and chayns.intercom.sendMessageToPage({text: sendtext}).then(function(data){}); and the data result is what you see above.

**Comment by JonasGossens** [comment]
We fixed this problem in a private e-mail conversation.
